@startuml
!define RECTANGLE_COLOR #ADD8E6
!define RECTANGLE_COLOR_2 #98FB98
!define TEXT_COLOR black

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Diagrama de Contêineres - Gabinete de Orçamento / Financeiro / Operações

Person(InternalUsers, "Gabinete de Orçamento / Financeiro / Operações", "Usuários internos que gerenciam e avaliam RFPs")

System_Boundary(InternalSystem, "Sistema Principal - Gabinete de Orçamento / Financeiro / Operações") {
    Container(WebPageCollaborator, "Pag Web (Canal Colaborador)", "React", "Portal para gerenciamento de RFPs") 
    Container(OAM, "OAM", "Access Manager", "Gerenciamento de Acessos")
    Container(AzureFrontDoor, "Azure Front Door", "CDN", "Distribuição de conteúdo global")
    Container(APIIntegration1, "Integração [API Gateway]", "API Gateway", "Integração de Serviços")
    Container_Boundary(BackendSystem, "System Software") {
        Container(BusinessLogic, "Business Logic", "Java + Spring Boot", "Lógica de negócios do sistema")
        Container(ProposalService, "Proposal Service API", "Java + Spring Boot", "Serviço para gerenciar propostas de RFP")
        Container(UserService, "User Service API", "Java + Spring Boot", "Serviço para gerenciar usuários")
        Container(ReportingService, "Reporting Service API", "Java + Spring Boot", "Serviço para geração de relatórios")
        Container(Database, "Banco de Dados", "MySQL", "Banco de dados relacional para armazenamento de dados do sistema")
    }
    Container(Dashboard, "Dashboard", "Power BI", "Visualização de Dados")
    Container(ETL, "ETL", "Talend", "Processamento de Dados")
    Container(DataWarehouse, "Data Warehouse", "Azure Synapse Analytics", "Armazenamento de dados para análise")
}

Rel(InternalUsers, AzureFrontDoor, "Acessa conteúdo via CDN")
Rel(AzureFrontDoor, APIIntegration1, "Distribui conteúdo")
Rel(WebPageCollaborator, OAM, "Autentica Usuários Internos")
Rel( UserService, OAM, "Gerencia Sessões")
Rel(APIIntegration1, WebPageCollaborator, "Solicita acesso Web")
Rel(APIIntegration1, ProposalService, "Fornece Dados de Propostas")
Rel(BusinessLogic, Database, "Armazena Dados")
Rel(BusinessLogic, ETL, "Envia Dados Brutos")
Rel(ETL, DataWarehouse, "Transfere Dados Processados")
Rel(DataWarehouse, Dashboard, "Fornece Dados para Relatórios")
Rel(BusinessLogic, Dashboard, "Fornece Dados em Tempo Real")

note left of InternalSystem
    O Gabinete de Orçamento precisa de um sistema para gerenciar RFPs,
    avaliar propostas, e visualizar relatórios financeiros e de desempenho.
end note

note left of WebPageCollaborator
    Um usuário do Gabinete de Orçamento cadastra uma nova RFP no sistema,
    preenchendo os detalhes do projeto e os critérios de avaliação.
end note

note right of Dashboard
    Visualização de relatórios financeiros e operacionais em tempo real.
end note
@enduml