@startuml
!define RECTANGLE_COLOR #ADD8E6
!define RECTANGLE_COLOR_2 #98FB98
!define TEXT_COLOR black

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam ArrowColor black
skinparam ArrowThickness 1
skinparam DefaultFontColor black

title Diagrama de Contêineres - Empresas Interessadas

Person(Companies, "Empresas Interessadas", "Empresas que submetem propostas de RFP")

System_Boundary(ExternalSystem, "Sistema Principal - Empresas Interessadas") {
    Container(WebPageSupplier, "Pag Web (Canal Fornecedor)", "React", "Portal para envio de propostas de RFP")
    Container(OAM, "OAM", "Access Manager", "Gerenciamento de Acessos")
    Container(AzureFrontDoor, "Azure Front Door", "CDN", "Distribuição de conteúdo global")
    Container(APIIntegration2, "Integração [API Gateway]", "APIM", "Integração de Serviços")
    Container_Boundary(BackendSystem, "System Software") {
        Container(ProposalService, "Proposal Service API", "Java + Spring Boot", "Serviço para gerenciar propostas de RFP")
    }
}

Rel(Companies, AzureFrontDoor, "1. Acessa conteúdo via CDN")
Rel(AzureFrontDoor, APIIntegration2, "2. Distribui conteúdo")
Rel(WebPageSupplier, OAM, "3. Autentica Usuários Externos")
Rel(ProposalService, OAM, "6. Gerencia Sessões")
Rel(APIIntegration2, WebPageSupplier, "5. Acessa Web")
Rel(APIIntegration2, ProposalService, "4. Fornece Dados de Propostas")

note right of ExternalSystem
    Empresas interessadas acessam o sistema para enviar propostas
    de RFP, incluindo detalhes técnicos e comerciais.
end note

note right of WebPageSupplier
    Empresas interessadas acessam o portal e enviam suas propostas
    de RFP, incluindo detalhes técnicos e comerciais.
end note
@enduml
